name: Bicep Validation

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  validate:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Build Bicep templates
        run: |
          find . -name "*.bicep" -print0 | xargs -0 -n1 az bicep build --file
